modLoader="javafml"
loaderVersion="[28,)"
# The license for you mod. This is mandatory metadata and allows for easier comprehension of your redistributive properties.
# Review your options at https://choosealicense.com/. All rights reserved is the default copyright stance, and is thus the default here.
license="All rights reserved"
[[mods]]
modId="itemtransformhelper"
version="${file.jarVersion}"
displayName="Item Transform Helper"
credits="The Forge, MCP, and FML guys. Maruohon"
authors="TGG, Romejanic, lehjr"
description="Interactively change the position, scale, and rotation of an item"
[[dependencies.itemtransformhelper]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.itemtransformhelper]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
